"""BrandGroup model for LLM-generated pricing data."""
from datetime import datetime
from decimal import Decimal
from sqlalchemy import String, DECIMAL, TIMESTAMP, CheckConstraint, Index
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from shared.database import Base


class BrandGroup(Base):
    """
    Brand×Group pricing data generated by LLM.

    Stores base prices and expected values for a specific brand and product group combination.
    Example: Levi's + jeans → base_price=25€, expected_origins=["USA", "Mexico"]
    """
    __tablename__ = "brand_groups"
    __table_args__ = (
        CheckConstraint('base_price >= 5.00 AND base_price <= 500.00', name='ck_brand_groups_base_price'),
        CheckConstraint('condition_sensitivity >= 0.5 AND condition_sensitivity <= 1.5', name='ck_brand_groups_sensitivity'),
        Index('idx_brand_groups_brand', 'brand'),
        Index('idx_brand_groups_group', 'group_name'),
        Index('idx_brand_groups_created_at', 'created_at'),
        {'schema': 'public'}
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    brand: Mapped[str] = mapped_column(String(100), nullable=False)
    group_name: Mapped[str] = mapped_column(String(50), nullable=False)
    base_price: Mapped[Decimal] = mapped_column(DECIMAL(10, 2), nullable=False)
    expected_origins: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    expected_decades: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    expected_trends: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    condition_sensitivity: Mapped[Decimal] = mapped_column(DECIMAL(3, 2), nullable=False, default=Decimal("1.0"))
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<BrandGroup(brand='{self.brand}', group='{self.group_name}', base_price={self.base_price})>"
