"""Model model for LLM-generated model-specific pricing data."""
from datetime import datetime
from decimal import Decimal
from sqlalchemy import String, DECIMAL, TIMESTAMP, CheckConstraint, Index
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from shared.database import Base


class Model(Base):
    """
    Model-specific pricing data generated by LLM.

    Stores coefficient and expected features for a specific model within a brand×group.
    Example: Levi's + jeans + 501 → coefficient=1.4, expected_features=[]
    Example: Levi's + jeans + Big E → coefficient=2.5, expected_features=["selvedge", "chain_stitching"]
    """
    __tablename__ = "models"
    __table_args__ = (
        CheckConstraint('coefficient >= 0.5 AND coefficient <= 3.0', name='ck_models_coefficient'),
        Index('idx_models_brand', 'brand'),
        Index('idx_models_group', 'group_name'),
        Index('idx_models_brand_group', 'brand', 'group_name'),
        Index('idx_models_created_at', 'created_at'),
        {'schema': 'public'}
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    brand: Mapped[str] = mapped_column(String(100), nullable=False)
    group_name: Mapped[str] = mapped_column(String(50), nullable=False)
    model: Mapped[str] = mapped_column(String(100), nullable=False)
    coefficient: Mapped[Decimal] = mapped_column(DECIMAL(4, 2), nullable=False, default=Decimal("1.0"))
    expected_features: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<Model(brand='{self.brand}', group='{self.group_name}', model='{self.model}', coeff={self.coefficient})>"
