"""Create public schema tables

Revision ID: fa11e75af96b
Revises: 
Create Date: 2025-12-04 12:29:59.133915+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa11e75af96b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'SUSPENDED', 'FLAGGED', 'SOLD', 'ARCHIVED', name='product_status'), nullable=False),
    sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_product_sku')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.create_table('platform_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('VINTED', 'EBAY', 'ETSY', name='platform_type'), nullable=False),
    sa.Column('stoflow_category', sa.String(length=255), nullable=False),
    sa.Column('platform_category', sa.String(length=255), nullable=False),
    sa.Column('platform_category_id', sa.String(length=100), nullable=True),
    sa.Column('attributes_mapping', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'stoflow_category', name='uq_platform_stoflow_category'),
    schema='public'
    )
    op.create_index(op.f('ix_public_platform_mappings_id'), 'platform_mappings', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_platform_mappings_platform'), 'platform_mappings', ['platform'], unique=False, schema='public')
    op.create_index(op.f('ix_public_platform_mappings_stoflow_category'), 'platform_mappings', ['stoflow_category'], unique=False, schema='public')
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenants_email'), 'tenants', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tenants_id'), 'tenants', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenants_name'), 'tenants', ['name'], unique=True, schema='public')
    op.create_table('ai_generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_logs_cached'), 'ai_generation_logs', ['cached'], unique=False)
    op.create_index(op.f('ix_ai_generation_logs_created_at'), 'ai_generation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_generation_logs_id'), 'ai_generation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generation_logs_model'), 'ai_generation_logs', ['model'], unique=False)
    op.create_index(op.f('ix_ai_generation_logs_product_id'), 'ai_generation_logs', ['product_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', name='subscription_status'), nullable=False),
    sa.Column('max_products', sa.Integer(), nullable=False),
    sa.Column('max_publications_per_month', sa.Integer(), nullable=False),
    sa.Column('monthly_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_subscriptions_id'), 'subscriptions', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_subscriptions_status'), 'subscriptions', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=True, schema='public')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_tenant_id'), 'users', ['tenant_id'], unique=False, schema='public')
    op.create_table('publication_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='publication_status'), nullable=False),
    sa.Column('platform_product_id', sa.String(length=100), nullable=True),
    sa.Column('platform_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_history_id'), 'publication_history', ['id'], unique=False)
    op.create_index(op.f('ix_publication_history_platform'), 'publication_history', ['platform'], unique=False)
    op.create_index(op.f('ix_publication_history_product_id'), 'publication_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_publication_history_published_at'), 'publication_history', ['published_at'], unique=False)
    op.create_index(op.f('ix_publication_history_status'), 'publication_history', ['status'], unique=False)
    op.create_table('vinted_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('vinted_product_id', sa.String(length=100), nullable=True),
    sa.Column('vinted_url', sa.String(length=500), nullable=True),
    sa.Column('vinted_category_id', sa.String(length=100), nullable=True),
    sa.Column('vinted_raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vinted_products_id'), 'vinted_products', ['id'], unique=False)
    op.create_index(op.f('ix_vinted_products_product_id'), 'vinted_products', ['product_id'], unique=True)
    op.create_index(op.f('ix_vinted_products_vinted_product_id'), 'vinted_products', ['vinted_product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vinted_products_vinted_product_id'), table_name='vinted_products')
    op.drop_index(op.f('ix_vinted_products_product_id'), table_name='vinted_products')
    op.drop_index(op.f('ix_vinted_products_id'), table_name='vinted_products')
    op.drop_table('vinted_products')
    op.drop_index(op.f('ix_publication_history_status'), table_name='publication_history')
    op.drop_index(op.f('ix_publication_history_published_at'), table_name='publication_history')
    op.drop_index(op.f('ix_publication_history_product_id'), table_name='publication_history')
    op.drop_index(op.f('ix_publication_history_platform'), table_name='publication_history')
    op.drop_index(op.f('ix_publication_history_id'), table_name='publication_history')
    op.drop_table('publication_history')
    op.drop_index(op.f('ix_public_users_tenant_id'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_subscriptions_tenant_id'), table_name='subscriptions', schema='public')
    op.drop_index(op.f('ix_public_subscriptions_status'), table_name='subscriptions', schema='public')
    op.drop_index(op.f('ix_public_subscriptions_id'), table_name='subscriptions', schema='public')
    op.drop_table('subscriptions', schema='public')
    op.drop_index(op.f('ix_ai_generation_logs_product_id'), table_name='ai_generation_logs')
    op.drop_index(op.f('ix_ai_generation_logs_model'), table_name='ai_generation_logs')
    op.drop_index(op.f('ix_ai_generation_logs_id'), table_name='ai_generation_logs')
    op.drop_index(op.f('ix_ai_generation_logs_created_at'), table_name='ai_generation_logs')
    op.drop_index(op.f('ix_ai_generation_logs_cached'), table_name='ai_generation_logs')
    op.drop_table('ai_generation_logs')
    op.drop_index(op.f('ix_public_tenants_name'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_id'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_email'), table_name='tenants', schema='public')
    op.drop_table('tenants', schema='public')
    op.drop_index(op.f('ix_public_platform_mappings_stoflow_category'), table_name='platform_mappings', schema='public')
    op.drop_index(op.f('ix_public_platform_mappings_platform'), table_name='platform_mappings', schema='public')
    op.drop_index(op.f('ix_public_platform_mappings_id'), table_name='platform_mappings', schema='public')
    op.drop_table('platform_mappings', schema='public')
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
