"""Make user email globally unique

Revision ID: bcd3b2f021aa
Revises: fa11e75af96b
Create Date: 2025-12-04 14:58:48.155458+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd3b2f021aa'
down_revision: Union[str, None] = 'fa11e75af96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriptions_tenant_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('uq_user_tenant_email', 'users', type_='unique')
    op.drop_index('ix_public_users_email', table_name='users')
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.create_index('ix_public_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_user_tenant_email', 'users', ['tenant_id', 'email'])
    op.drop_constraint(None, 'subscriptions', schema='public', type_='foreignkey')
    op.create_foreign_key('subscriptions_tenant_id_fkey', 'subscriptions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
