"""seed_brands_streetwear_luxury

Revision ID: 13bf2ac0415d
Revises: a526b508fa0e
Create Date: 2026-01-22 11:03:06.768373+01:00

Adds 300+ streetwear, luxury, skate, and fashion brands to the brands table.
"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '13bf2ac0415d'
down_revision: Union[str, None] = 'a526b508fa0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# List of brands to add
BRANDS = [
    "Abercrombie & Fitch",
    "A-Cold-Wall*",
    "Adam Kimmel",
    "Adio",
    "Admiral",
    "Aeropostale",
    "Aimé Leon Dore",
    "Airwalk",
    "Albam",
    "Alden",
    "Alexander McQueen",
    "Alexander Wang",
    "Alien Workshop",
    "Alk Phenix",
    "AllSaints",
    "Alpha Industries",
    "Alphanumeric",
    "Ambush",
    "Ami Paris",
    "Amiri",
    "Andrea Crews",
    "Ann Demeulemeester",
    "Anti Social Social Club",
    "Aquascutum",
    "Arket",
    "Armor-Lux",
    "Asics",
    "Aspesi",
    "Atmosphere",
    "Awake Ny",
    "Balenciaga",
    "Balmain",
    "Barbour",
    "Beams",
    "Beams Plus",
    "Belstaff",
    "Ben Sherman",
    "Billionaire Boys Club",
    "Billabong",
    "Birkenstock",
    "Bleu De Paname",
    "Blundstone",
    "Boncoto",
    "Botter",
    "Bounty Hunter",
    "Brice",
    "Brooks Brothers",
    "Brunello Cucinelli",
    "Buffalo",
    "C.P. Company",
    "C1rca",
    "Cabela's",
    "Canada Goose",
    "Canali",
    "Casey Casey",
    "Caterpillar",
    "Cav Empt",
    "Celine",
    "Chalk Line",
    "Chanel",
    "Christian Dior",
    "Christian Louboutin",
    "Christopher Raeburn",
    "Church's",
    "Cio",
    "Circa",
    "Clarks",
    "Closed",
    "Colette",
    "Columbia",
    "Comme Des Garçons",
    "Common Projects",
    "Converse",
    "Cos",
    "Craig Green",
    "Creature",
    "Cross Colours",
    "Custo Barcelona",
    "D&G",
    "Daiki Suzuki",
    "Daily Paper",
    "Dada Supreme",
    "Damir Doma",
    "Danton",
    "Dc Shoes",
    "Descente",
    "Desigual",
    "Deus Ex Machina",
    "Diadora",
    "Dior Homme",
    "Dita",
    "Doc Martens",
    "Dolce & Gabbana",
    "Dr. Martens",
    "Dries Van Noten",
    "Drôle De Monsieur",
    "Dvs",
    "Eddie Bauer",
    "Element",
    "Ellesse",
    "Emerica",
    "Enjoi",
    "Erdem",
    "Etnies",
    "Eytys",
    "Facetasm",
    "Faith Connexion",
    "Fallen",
    "Fear Of God",
    "Fendi",
    "Fila",
    "Filson",
    "Finisterre",
    "Fjällräven",
    "Fred Perry",
    "Ganryu",
    "Gant",
    "Gas",
    "Gaultier",
    "Givenchy",
    "Globe",
    "Golden Goose",
    "Golf Wang",
    "Gosha Rubchinskiy",
    "Gotcha",
    "Griffin",
    "Gucci",
    "Haider Ackermann",
    "Hansen",
    "Harmony",
    "Helly Hansen",
    "Helmut Lang",
    "Henri Lloyd",
    "Hermès",
    "Hoka One One",
    "Hollister",
    "Human Made",
    "Hussein Chalayan",
    "Hydra",
    "Iceberg",
    "Independent",
    "Inverallan",
    "Isabel Marant",
    "Issey Miyake",
    "Jack & Jones",
    "Jacquemus",
    "Jaded London",
    "Jean Paul Gaultier",
    "Jeffer",
    "Jil Sander",
    "Jimmy Choo",
    "John Elliott",
    "John Galliano",
    "Johnny Blaze",
    "Junya Watanabe",
    "Just Cavalli",
    "Jw Anderson",
    "K-Way",
    "K1x",
    "Kangol",
    "Kappa",
    "Kenzo",
    "Kickz",
    "Kith",
    "Knowledge Cotton Apparel",
    "Kris Van Assche",
    "Ksubi",
    "L.L. Bean",
    "Lakai",
    "Lanvin",
    "Le Coq Sportif",
    "Le Laboureur",
    "Liam Hodges",
    "Loewe",
    "Lois",
    "Lonsdale",
    "Loro Piana",
    "Lost Enterprises",
    "Lot 29",
    "Lotto",
    "Louis Vuitton",
    "Love Moschino",
    "Lowe Alpine",
    "Lugz",
    "Lyle & Scott",
    "Mackintosh",
    "Maison Kitsuné",
    "Maison Margiela",
    "Makaveli Branded",
    "Mammut",
    "Manastash",
    "Mango Man",
    "Marc Jacobs",
    "Marcelo Burlon",
    "Margaret Howell",
    "Marmot",
    "Martine Rose",
    "Massimo Dutti",
    "Mastermind Japan",
    "Mavi",
    "Mcm",
    "Merrell",
    "Millet",
    "Mister Freedom",
    "Miu Miu",
    "Moncler",
    "Moschino",
    "Mountain Hardwear",
    "Muji",
    "Nanamica",
    "Needles",
    "Neil Barrett",
    "New Balance",
    "Noah",
    "Norse Projects",
    "Nutmeg",
    "O'Neill",
    "Oakley",
    "Off-White",
    "Officine Generale",
    "On Running",
    "Orcival",
    "Orvis",
    "Osiris",
    "Ovadia & Sons",
    "Oxbow",
    "Palm Angels",
    "Paraboot",
    "Parra",
    "Patagonia",
    "Paul & Shark",
    "Paul Smith",
    "Pendleton",
    "Penfield",
    "Philipp Plein",
    "Pigalle",
    "Pnb Nation",
    "Powell Peralta",
    "Prada",
    "Pro Player",
    "Promod",
    "Pull & Bear",
    "Pyrenex",
    "Quechua Vintage",
    "Quiksilver",
    "Raf Simons",
    "Red Kap",
    "Red Wing",
    "Reiss",
    "Represent",
    "Rhude",
    "Rick Owens",
    "Rip Curl",
    "Ripndip",
    "Roberto Cavalli",
    "Rochas",
    "Ronin",
    "Round House",
    "Ruff Ryders",
    "Russell Athletic",
    "Rusty",
    "Sacai",
    "Saint James",
    "Saint Laurent",
    "Salomon",
    "Sandro",
    "Santa Cruz",
    "Sasquatchfabrix",
    "Saturday Nyc",
    "Saucony",
    "Schott Nyc",
    "Sergio Tacchini",
    "Shady Ltd",
    "Shein",
    "Sir Benni Miles",
    "Skechers",
    "Sophnet",
    "Soulland",
    "Spitfire",
    "Sporty & Rich",
    "Spyder",
    "Stone Island",
    "Stone Island Shadow Project",
    "Superdry",
    "Superga",
    "Takahiromiyashita The Soloist",
    "Ten C",
    "The Kooples",
    "The Real Mccoy's",
    "Thom Browne",
    "Thrasher",
    "Tom Ford",
    "Tommy Jeans",
    "Topman",
    "Town & Country Surf",
    "Triple 5 Soul",
    "Tsumori Chisato",
    "Umbro",
    "Undercover",
    "Uniform Experiment",
    "Valentino",
    "Versace",
    "Vetra",
    "Vilebrequin",
    "Visvim",
    "Vivienne Westwood",
    "Wacko Maria",
    "Walls",
    "Weekday",
    "White Mountaineering",
    "Wild Things",
    "Woolrich",
    "World Industries",
    "Y-3",
    "Yohji Yamamoto",
    "Yves Saint Laurent",
    "Zadig & Voltaire",
    "Zero",
]


def upgrade() -> None:
    conn = op.get_bind()

    # Bulk insert with ON CONFLICT DO NOTHING (idempotent)
    for brand_name in BRANDS:
        conn.execute(
            text("""
                INSERT INTO product_attributes.brands (name)
                VALUES (:name)
                ON CONFLICT (name) DO NOTHING
            """),
            {"name": brand_name}
        )


def downgrade() -> None:
    conn = op.get_bind()

    # Remove only the brands added by this migration
    for brand_name in BRANDS:
        conn.execute(
            text("""
                DELETE FROM product_attributes.brands
                WHERE name = :name
            """),
            {"name": brand_name}
        )
