"""seed_brands_extended_fashion

Revision ID: 922bd876f757
Revises: 13bf2ac0415d
Create Date: 2026-01-22 11:10:31.586957+01:00

Adds 700+ additional fashion, sportswear, and lifestyle brands to the brands table.
"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '922bd876f757'
down_revision: Union[str, None] = '13bf2ac0415d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# List of brands to add
BRANDS = [
    "10.Deep",
    "11 Degrees",
    "1017 Alyx 9Sm",
    "424",
    "5.11 Tactical",
    "66 North",
    "7 For All Mankind",
    "Aape By A Bathing Ape",
    "Ader Error",
    "Adsum",
    "Aeronautica Militare",
    "Aigle",
    "Airness",
    "Alife",
    "Alpha Tauri",
    "Altamont",
    "American Apparel",
    "American Eagle",
    "American Vintage",
    "Angelo Litrico",
    "Anine Bing",
    "Anti Hero",
    "Antony Morato",
    "Armani Collezioni",
    "Armani Exchange",
    "Armani Jeans",
    "Arthur Galan",
    "Asos Design",
    "Asos White",
    "Asphalt Yacht Club",
    "Assos",
    "Atelier De Production Et De Creation",
    "Aubin & Wills",
    "Aviator Nation",
    "Azzaro",
    "Balibaris",
    "Bally",
    "Balmain Paris",
    "Bandit",
    "Baracuta",
    "Bark",
    "Barneys New York",
    "Bellfield",
    "Bench",
    "Benetton",
    "Bering",
    "Berluti",
    "Best Company",
    "Bexley",
    "Big Ben",
    "Bikkembergs",
    "Bill Tornade",
    "Billionaire",
    "Black Scale",
    "Blk Dnm",
    "Blood Brother",
    "Bobbies",
    "Boggi Milano",
    "Bogner",
    "Bombers Original",
    "Bones",
    "Bonne Gueule",
    "Boohoo Man",
    "Boris Bidjan Saberi",
    "Bottega Veneta",
    "Boxfresh",
    "Boy London",
    "Brandit",
    "Breitling",
    "Brioni",
    "Browning",
    "Brunotti",
    "Bullrot",
    "Bullrot Wear",
    "Burlington",
    "Burton Menswear",
    "By Parra",
    "By Walid",
    "C&A",
    "C17",
    "Cacharel",
    "Calvin Klein Jeans",
    "Camel Active",
    "Camp David",
    "Canadian Peak",
    "Canterbury",
    "Capalbio",
    "Captain Fin",
    "Carven",
    "Castelli",
    "Cdg Play",
    "Cedar Wood State",
    "Cerruti 1881",
    "Charles & Keith",
    "Chipie",
    "Chloé",
    "Christian Lacroix",
    "Chrome Hearts",
    "Cinque",
    "Cks",
    "Clockhouse",
    "Club Monaco",
    "Cmmmn Swdn",
    "Coa",
    "Cogi",
    "Colmar",
    "Colours Of Alexander Julian",
    "Columbia Pfg",
    "Com8",
    "Comme Des Garçons Play",
    "Commune De Paris",
    "Comptoir Des Cotonniers",
    "Coolcat",
    "Corneliani",
    "Cortefiel",
    "Costume National",
    "Cottonfield",
    "Country Road",
    "Creek",
    "Creeks",
    "Criminal Damage",
    "Crocs",
    "Crombie",
    "Cutter & Buck",
    "Cycle",
    "D'urban",
    "Dainese",
    "Dakine",
    "Dale Of Norway",
    "Damart",
    "Daniel Cremieux",
    "Daniel Hechter",
    "Daniele Fiesoli",
    "Darylstudio",
    "Dc",
    "Ddp",
    "De Fursac",
    "Dead Stock",
    "Deathworld",
    "Dedicated",
    "Defend Paris",
    "Degré 7",
    "Denimbird",
    "Denim & Supply Ralph Lauren",
    "Derek Rose",
    "Devred",
    "Dia",
    "Diadora Heritage",
    "Diamond Supply Co.",
    "Dime Mtl",
    "Dirk Bikkembergs",
    "District",
    "Dockers",
    "Doomsday",
    "Dr. Denim",
    "Drake's",
    "Drapeau Noir",
    "Drole De Monsieur",
    "Dsquared2",
    "Dubbleworks",
    "Dunhill",
    "Duvetica",
    "Ea7",
    "Eastpak",
    "Ecko Red",
    "Eleven Paris",
    "Elite",
    "Elwood",
    "Emporio Armani",
    "Enfants Riches Deprimes",
    "Epaulet",
    "Equinox",
    "Erigo",
    "Ermenegildo Zegna",
    "Esemplare",
    "Etro",
    "Ex Officio",
    "Eye",
    "Façonnable",
    "Farah",
    "Fashion Nova",
    "Fila Vintage",
    "Filling Pieces",
    "Finamore",
    "Fiorucci",
    "Firetrap",
    "Five Brother",
    "Flying Machine",
    "Folk",
    "Foot Locker",
    "Forvert",
    "Fossil",
    "Fox Racing",
    "Franklin & Marshall",
    "French Connection",
    "Fruit Of The Loom",
    "Furygan",
    "Fusalp",
    "Gaastra",
    "Gabicci",
    "Galeries Lafayette",
    "Galliano",
    "Garcia",
    "Gaudi",
    "Geographical Norway",
    "George",
    "Gildan",
    "Giorgio Armani",
    "Gitman Vintage",
    "Gloverall",
    "Golden Bear",
    "Good For Nothing",
    "Goose & Gander",
    "Gore-Tex",
    "Goyard",
    "Gran Sasso",
    "Greg Lauren",
    "Grenfell",
    "Grenson",
    "Grimey",
    "Guess Jeans",
    "Guide London",
    "Gul",
    "Gunex",
    "Gurteen",
    "Gym King",
    "Gymshark",
    "Hackett",
    "Hanes",
    "Hanon",
    "Happy Socks",
    "Hard Rock Cafe",
    "Harley Davidson",
    "Harris Tweed",
    "Harro",
    "Harry Brown",
    "Hart Schaffner Marx",
    "Hast",
    "Head",
    "Heart & Dagger",
    "Heire",
    "Heschung",
    "Hilfiger Denim",
    "Homeboy",
    "Homecore",
    "Homme Plissé Issey Miyake",
    "Hood By Air",
    "Hoodrich",
    "Hope",
    "Horsefeathers",
    "House Of Sunny",
    "Hub",
    "Hudson",
    "Hugo",
    "Hummel",
    "Hundred",
    "Hunter",
    "Hype",
    "Icebreaker",
    "Ikks",
    "Imperial",
    "In Gold We Trust",
    "Incotex",
    "Industrie",
    "Ines De La Fressange",
    "Insight",
    "Iriedaily",
    "Iron And Resin",
    "Isaia",
    "Island",
    "Iuter",
    "J. Crew",
    "J. Lindeberg",
    "J. Press",
    "Jack Wills",
    "Jacob Cohen",
    "Jagger",
    "Jaguar",
    "James Perse",
    "Japan Rags",
    "Jasper Conran",
    "Jbrand",
    "Jc De Castelbajac",
    "Jeff Hamilton",
    "Jerzees",
    "Jigsaw",
    "John Bull",
    "John Smedley",
    "John Varvatos",
    "Joop!",
    "Jordan",
    "Joules",
    "Joyrich",
    "Juun.J",
    "K-Swiss",
    "Kangaroos",
    "Karu Research",
    "Kathmandu",
    "Katin",
    "Kaws",
    "Keds",
    "Keen",
    "Kenneth Cole",
    "Kids Super",
    "Killy",
    "King Apparel",
    "Kings Will Dream",
    "Kiton",
    "Kjus",
    "Kokon To Zai",
    "Komodo",
    "Kookai",
    "Kulte",
    "L'étrange Noël De Monsieur Jack",
    "La Martina",
    "Lacoste Live",
    "Lady Enyce",
    "Lafuma",
    "Le Glazik",
    "Le Shark",
    "Le Temps Des Cerises",
    "Lee 101",
    "Lego",
    "Les Benjamins",
    "Les Deux",
    "Les Hommes",
    "Libertine-Libertine",
    "Liberto",
    "Life Is Good",
    "Lindbergh",
    "Liu Jo",
    "Live Mechanics",
    "Lloyd",
    "Loavies",
    "Loom",
    "Loreak Mendian",
    "Lost",
    "Lot 78",
    "Lovely",
    "Low Brand",
    "Lrg",
    "Lucien Pellat Finet",
    "Lucky Brand",
    "Ma.Strum",
    "Madewell",
    "Mainio",
    "Maison Labiche",
    "Maison Martin Margiela",
    "Maje",
    "Malo",
    "Manolo Blahnik",
    "Marc O'Polo",
    "Marithé + François Girbaud",
    "Marshall Artist",
    "Marvel",
    "Massimo",
    "Matinique",
    "Maui And Sons",
    "Maverick",
    "Max Mara",
    "Mcgregor",
    "Mckenzie",
    "Mcq Alexander Mcqueen",
    "Mephisto",
    "Merc",
    "Mercier",
    "Metallica",
    "Mexx",
    "Michael Kors",
    "Michelin",
    "Mickey Mouse",
    "Micro",
    "Microsoft",
    "Midas",
    "Mki Miyuki Zoku",
    "Mmlg",
    "Mnml",
    "Mobil",
    "Modern",
    "Mojo",
    "Mooks",
    "Moon",
    "Moose Knuckles",
    "Morgan",
    "Moss Bros",
    "Mossy Oak",
    "Mother",
    "Motor",
    "Mountain",
    "Mr P.",
    "Mustang",
    "My",
    "N.Hoolywood",
    "Na-Kd",
    "Naf Naf",
    "Name It",
    "Nanushka",
    "Nasa",
    "National Geographic",
    "Native Youth",
    "Nautica",
    "Navigare",
    "Nba",
    "Ncaa",
    "Nena & Pasadena",
    "Neuw",
    "Nevica",
    "New Era",
    "New Look",
    "New Man",
    "Next",
    "Nhl",
    "Nicce",
    "Nicholas Deakins",
    "Nickelson",
    "Nicole Farhi",
    "Nike Acg",
    "Nike Sb",
    "Nikelab",
    "Nirvana",
    "No Nationality",
    "Nn07",
    "Noble",
    "Noir",
    "Noon Goons",
    "North Sails",
    "Number (N)Ine",
    "Octobers Very Own (Ovo)",
    "Octobre Editions",
    "Odd Future",
    "Office",
    "Officine Creative",
    "Oilily",
    "Old Navy",
    "Old River",
    "Oliver Spencer",
    "Omg",
    "Only",
    "Only & Sons",
    "Only Ny",
    "Opening Ceremony",
    "Original Penguin",
    "Orlebar Brown",
    "Orsay",
    "Osprey",
    "Oysho",
    "P.E Nation",
    "Paco Rabanne",
    "Palmes",
    "Paname",
    "Pandora",
    "Pangaia",
    "Paolo Pecora",
    "Parajumpers",
    "Paris",
    "Parker",
    "Patta",
    "Paul And Shark",
    "Peak Performance",
    "Pepsi",
    "Percival",
    "Perfect Moment",
    "Perry Ellis",
    "Petrol Industries",
    "Peuterey",
    "Pharell",
    "Pierre Balmain",
    "Pierre Cardin",
    "Pimkie",
    "Pink Floyd",
    "Pioneer",
    "Pirelli",
    "Places + Faces",
    "Plain",
    "Planet",
    "Platinum",
    "Playboy",
    "Pleasures",
    "Plenty",
    "Polo Golf",
    "Polo Jeans",
    "Polo Ralph Lauren",
    "Polo Sport",
    "Porsche",
    "Post Archive Faction",
    "Prada Sport",
    "Pretty Green",
    "Primark",
    "Primitive",
    "Pringle Of Scotland",
    "Project X Paris",
    "Propper",
    "Protest",
    "Ps Paul Smith",
    "Pyer Moss",
    "Pyrex",
    "Qasimi",
    "Quechua",
    "R13",
    "Rains",
    "Rapha",
    "Ravin",
    "Ray-Ban",
    "Re/Done",
    "Readymade",
    "Real",
    "Realtree",
    "Red Skins",
    "Reef",
    "Religion",
    "Remington",
    "Replay",
    "Reserved",
    "Resteröds",
    "Retro",
    "Review",
    "Revolution",
    "Rg512",
    "Rifle",
    "River Island",
    "Roark",
    "Rockport",
    "Rodd & Gunn",
    "Rolex",
    "Rolling Stones",
    "Rossignol",
    "Rotary",
    "Rothco",
    "Route 66",
    "Royal Wear",
    "Rrl",
    "Rso",
    "Rude",
    "Rvca",
    "S.Oliver",
    "Saint",
    "Saks Fifth Avenue",
    "Salamander",
    "Salt",
    "Samsoe & Samsoe",
    "Santoni",
    "Saturdays Nyc",
    "Save The Duck",
    "Scalpers",
    "Schiesser",
    "Scotch & Soda",
    "Scott",
    "Sea",
    "Sealup",
    "Seidensticker",
    "Selected Homme",
    "Seven",
    "Sex",
    "Shark",
    "Shell",
    "Shoei",
    "Siksilk",
    "Silent Damir Doma",
    "Silk",
    "Silver",
    "Sim",
    "Simon",
    "Simple",
    "Sisley",
    "Sixth June",
    "Skin",
    "Slam Jam",
    "Sleep",
    "Smart",
    "Smiley",
    "Smith",
    "Smog",
    "Smoke",
    "Snipes",
    "Soft",
    "Solid",
    "Solovair",
    "Son Of A Stag",
    "Sonia Rykiel",
    "Sound",
    "Source",
    "South",
    "Spalding",
    "Speedo",
    "Spider",
    "Spiewak",
    "Spirit",
    "Sport",
    "Sportmax",
    "Sporty",
    "Springfield",
    "Standard",
    "Stanley",
    "Star",
    "State",
    "Stefanel",
    "Stella Mccartney",
    "Stenströms",
    "Steve Madden",
    "Strellson",
    "Studio",
    "Style",
    "Suitsupply",
    "Sun",
    "Sun Valley",
    "Sun68",
    "Sundek",
    "Sunflower",
    "Sunspel",
    "Super",
    "Supra",
    "Surf",
    "Surplus",
    "Sweet",
    "Swing",
    "Swiss",
    "T&C Surf Designs",
    "T-Mobile",
    "Tailor",
    "Takeshy Kurosawa",
    "Talbots",
    "Talking Heads",
    "Target",
    "Tasc",
    "Tba",
    "Tc",
    "Tdk",
    "Team",
    "Tealer",
    "Tech",
    "Ted Baker",
    "Tee",
    "Tek",
    "Ten",
    "Tenson",
    "Teva",
    "Tex",
    "The Bradery",
    "The Broken Arm",
    "The Hundreds",
    "Theory",
    "Thomas Burberry",
    "Thor",
    "Thrift",
    "Throwback",
    "Tiger Of Sweden",
    "Time",
    "Tintin",
    "Tn",
    "Tod's",
    "Tom Tailor",
    "Toms",
    "Tony",
    "Top",
    "Topper",
    "Tor",
    "Tory Burch",
    "Toteme",
    "Tour",
    "Toy",
    "Track",
    "Trad",
    "Traffic",
    "Training",
    "Tramarossa",
    "Trapstar",
    "Trasher",
    "Travel",
    "Tretorn",
    "Triple",
    "True",
    "Trussardi",
    "Tsubi",
    "Tu",
    "Tumi",
    "Ty",
    "U.S. Polo Assn.",
    "Ugg",
    "Under",
    "Uniform",
    "United",
    "United Colors Of Benetton",
    "Universal",
    "Unknown",
    "Urban",
    "Urban Outfitters",
    "Us",
    "Us Army",
    "Used",
    "Valet",
    "Van",
    "Vanessa Bruno",
    "Varsity",
    "Vart",
    "Vea",
    "Velvet",
    "Venice",
    "Vera Wang",
    "Versace Jeans Couture",
    "Vest",
    "Vetements",
    "Vf",
    "Via",
    "Vibram",
    "Vicomte A.",
    "Victoria Beckham",
    "Victoria's Secret",
    "Viking",
    "Vintage",
    "Vision",
    "Vision Street Wear",
    "Vit",
    "Vivienne",
    "Vlone",
    "Vogue",
    "Volkswagen",
    "Von Dutch",
    "Vuarnet",
    "W",
    "Wasted Paris",
    "Wave",
    "We",
    "Weatherproof",
    "We11done",
    "Wemoto",
    "West",
    "Western",
    "Weston",
    "Whistles",
    "White",
    "Who Is Jacov",
    "Wild",
    "Will",
    "William",
    "Wilson",
    "Wins",
    "Wip",
    "Wolf",
    "Wolford",
    "Wood Wood",
    "Wool",
    "Work",
    "World",
    "Wwe",
    "Y Project",
    "Yale",
    "Yamamoto",
    "Yankee",
    "Ycc",
    "Ymc",
    "Yo",
    "Yonex",
    "York",
    "Young",
    "Yours",
    "Ysl",
    "Yves",
    "Z Brand",
    "Z Zegna",
    "Zaco",
    "Zalando",
    "Zanella",
    "Zanerobe",
    "Zara Man",
    "Zavetti Canada",
    "Zegna",
]


def upgrade() -> None:
    conn = op.get_bind()

    # Bulk insert with ON CONFLICT DO NOTHING (idempotent)
    for brand_name in BRANDS:
        conn.execute(
            text("""
                INSERT INTO product_attributes.brands (name)
                VALUES (:name)
                ON CONFLICT (name) DO NOTHING
            """),
            {"name": brand_name}
        )


def downgrade() -> None:
    conn = op.get_bind()

    # Remove only the brands added by this migration
    for brand_name in BRANDS:
        conn.execute(
            text("""
                DELETE FROM product_attributes.brands
                WHERE name = :name
            """),
            {"name": brand_name}
        )
