"""seed_brands_designer_contemporary

Revision ID: 2226fa17a30c
Revises: d6d39a258be5
Create Date: 2026-01-22 11:20:48.312428+01:00

Adds 800+ designer and contemporary fashion brands to the brands table.
"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '2226fa17a30c'
down_revision: Union[str, None] = 'd6d39a258be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# List of brands to add
BRANDS = [
    "032c",
    "7 Diamonds",
    "99%is",
    "A Kind Of Guise",
    "A.Testoni",
    "Acne",
    "Adieu Paris",
    "Afterhomework",
    "Agolde",
    "Ahluwalia",
    "Alanui",
    "Albram",
    "Aldo",
    "Alessandro Gherardi",
    "Alex Mill",
    "Allbirds",
    "Altea",
    "Alyx",
    "Amil",
    "Amish",
    "Andersen-Andersen",
    "Anderson & Sheppard",
    "Ann Taylor",
    "Antik Batik",
    "Aries",
    "Arpenteur",
    "Arte Antwerp",
    "Artful Dodger",
    "Asap Rocky",
    "Astrid Andersen",
    "Athleta",
    "Attico",
    "Aubercy",
    "Autry",
    "Avnier",
    "Axel Arigato",
    "Ba&Sh",
    "Bagutta",
    "Banana Republic",
    "Band Of Outsiders",
    "Barba Napoli",
    "Barena Venezia",
    "Bass Weejuns",
    "Bbc Ice Cream",
    "Beaubleu",
    "Bella Freud",
    "Berghaus",
    "Bernhard Willhelm",
    "Barena",
    "Black Diamond",
    "Black Yak",
    "Blauer",
    "Bleu De Chauffe",
    "Blind Reason",
    "Blumarine",
    "Bode",
    "Body Glove",
    "Boglioli",
    "Bolongaro Trevor",
    "Boramy Viguier",
    "Born X Raised",
    "Borsalino",
    "Boss Orange",
    "Brain Dead",
    "Brandy Melville",
    "Bronze 56k",
    "Brooks",
    "Brother Vellies",
    "Brunello",
    "Buffalo London",
    "Bylt",
    "C.C. Filson",
    "Cabourn",
    "Cafe Du Cycliste",
    "Callaway",
    "Calvin Klein 205W39Nyc",
    "Camper",
    "Caruso",
    "Casablanca",
    "Castaner",
    "Celine Homme",
    "Cerruti",
    "Cesare Attolini",
    "Chaco",
    "Charvet",
    "Chinatown Market",
    "Christian Wijnants",
    "Christopher Kane",
    "Christopher Shannon",
    "Chromat",
    "Churchs",
    "Ciele Athletics",
    "Circle Of Gentlemen",
    "Circolo 1901",
    "Citizens",
    "Claudio Orciani",
    "Club Of Gents",
    "Cmmmn",
    "Cole Buxton",
    "Common",
    "Conor",
    "Corridor",
    "Cosmic Wonder",
    "Cotopaxi",
    "Cottweiler",
    "Courreges",
    "Cpmm",
    "Craghoppers",
    "Creatures Of Comfort",
    "Crispi",
    "Cult Of Individuality",
    "Current/Elliott",
    "D.Gnak",
    "Dare 2b",
    "Dark",
    "Davoucci",
    "De Bonne Facture",
    "Dement",
    "Denim Tears",
    "Dernier & Hamon",
    "Des Petits Hauts",
    "Diemme",
    "Diesel Black Gold",
    "Dion Lee",
    "District Vision",
    "Django & Juliette",
    "Dmy By Dmy",
    "Doa",
    "Dres Van Noten",
    "Drifter",
    "Dsquared",
    "E. Tautz",
    "Eidos",
    "Eleventy",
    "Elka",
    "Emilio Pucci",
    "Endura",
    "Engineered",
    "Epaulet New York",
    "Equipment",
    "Eram",
    "Erba",
    "Eric Bompard",
    "Ermanno Scervino",
    "Escada",
    "Etudes",
    "Evisu Genes",
    "Express",
    "Faguo",
    "Faithfull The Brand",
    "Falke",
    "Fay",
    "Feit",
    "Fenty",
    "Ferrari",
    "Fitbit",
    "Flaneur",
    "Footjoy",
    "For Love And Lemons",
    "Frame Denim",
    "Francesco Smalto",
    "Frank And Oak",
    "Franklin Marshall",
    "Fucking Awesome",
    "Fujito",
    "G-Shock",
    "Ganni",
    "Gant Rugger",
    "Gas Bijoux",
    "Gcds",
    "Geox",
    "Gerry Weber",
    "Ghazal",
    "Ghost",
    "Gimo's",
    "Giuseppe Zanotti",
    "Givenchy Paris",
    "Gmbh",
    "Golden",
    "Goodfellow & Co",
    "Gorilla",
    "Gosha",
    "Gramicci Japan",
    "Grand Frank",
    "Greg",
    "Grifoni",
    "Grlfrnd",
    "GStar",
    "Guidi",
    "Guy Rover",
    "Hackett London",
    "Haikure",
    "Han Kjobenhavn",
    "Hanro",
    "Harridge",
    "Harrys Of London",
    "Hartford",
    "Hartwood",
    "Hawai",
    "Heimstone",
    "Helas",
    "Helmut",
    "Henderson",
    "Herno",
    "Hetregó",
    "Hiltl",
    "Hockey",
    "Hogan",
    "Holden",
    "Holubar",
    "Hommage",
    "Honorable",
    "Htc",
    "Hudson Jeans",
    "Human",
    "Huns",
    "Husky",
    "Hydroponic",
    "Ice Cream",
    "Iceberg History",
    "Ideal",
    "Ienki Ienki",
    "Ign",
    "Indochino",
    "Ines",
    "Injiri",
    "Inov-8",
    "Insight 51",
    "Iro",
    "Iron",
    "Isaora",
    "Issey",
    "Italo Ferretti",
    "J Brand",
    "Jacob",
    "Jagger & Lewis",
    "Jeckerson",
    "Jeffrey Campbell",
    "Jeremy Scott",
    "Jil",
    "Jim Rickey",
    "Jimmy Fairly",
    "John",
    "John Lobb",
    "Johnson Motors",
    "Josep",
    "Joseph",
    "Joseph Abboud",
    "Juicy Couture",
    "Julius",
    "Just",
    "K.Jacques",
    "K100",
    "Kamora",
    "Kappa Kontroll",
    "Kardo",
    "Karhu",
    "Karl",
    "Kate Spade",
    "Katin Usa",
    "Kaval",
    "Khrisjoy",
    "Kidill",
    "Kikwear",
    "Kill City",
    "King",
    "Kirk Originals",
    "Kmart",
    "Knickerbocker",
    "Kolor",
    "Kuhl",
    "L.B.M. 1911",
    "La Panoplie",
    "La Perla",
    "La Sportiva",
    "Labo Art",
    "Laboratoratori",
    "Lando",
    "Laneus",
    "Lardini",
    "Le Slip Français",
    "Le Tanneur",
    "Legion",
    "Les Filles D'en Rouje",
    "Les Tricots De Marcel",
    "Levis",
    "Linder",
    "Lindex",
    "Lion",
    "Lna",
    "Loewe Paula's Ibiza",
    "Loro",
    "Lotus",
    "Lou Dalton",
    "Love",
    "Low",
    "Lpa",
    "Lubiam",
    "Luciano Barbera",
    "Lululemon",
    "Lumberjack",
    "Luon",
    "M.Cohen",
    "Maap",
    "Mackage",
    "Madewell Men",
    "Maiden Noir",
    "Maison Chateau Rouge",
    "Maison Cornichon",
    "Maison Standards",
    "Majestic Filatures",
    "Malbon Golf",
    "Malbu",
    "Manolo",
    "Manuel Ritz",
    "Marc",
    "Marcelo",
    "Marché Noir",
    "Marco Polo",
    "Marni Men",
    "Marsèll",
    "Martin",
    "Martine",
    "Mastermind World",
    "Matches",
    "Mat de Misaine",
    "Matsuda",
    "Mauro Grifoni",
    "Max & Co",
    "Mcq",
    "Mercer Amsterdam",
    "Merz B. Schwanen",
    "Messagerie",
    "Michael",
    "Michiko Koshino",
    "Mihara",
    "Mike",
    "Mini",
    "Minimum",
    "Missoni",
    "Miu",
    "Mizuno",
    "Moda",
    "Mode",
    "Moero",
    "Momoni",
    "Monoprix",
    "Monttagne",
    "Moon Boot",
    "Moorer",
    "Morato",
    "Mos Mosh",
    "Mother Denim",
    "Mother Of Pearl",
    "Mountain Equipment",
    "Movic",
    "Msam",
    "Msgm",
    "Mugler",
    "Museum",
    "Musier Paris",
    "Myar",
    "N.Peal",
    "Napapijri Geographic",
    "Native",
    "Need",
    "Neil",
    "Nemen",
    "New",
    "Nice Kicks",
    "Nicholas Daley",
    "Nikelab Acg",
    "Nl",
    "Noak",
    "Nobis",
    "Noid",
    "Nona9on",
    "Norda",
    "Norse",
    "North",
    "Not",
    "Nour Hammour",
    "Noyoco",
    "Npeal",
    "Numph",
    "Oak",
    "Oakley Vintage",
    "Obey Propaganda",
    "Octobre",
    "Officine",
    "Olaf Hussein",
    "Old",
    "Oliver",
    "Oliver Peoples",
    "Olymp",
    "Omega",
    "On",
    "Oppo",
    "Orlebar",
    "Oroton",
    "Orslow",
    "Oscar De La Renta",
    "Otis",
    "Ottolinger",
    "Our",
    "Outdoor Voices",
    "P448",
    "Paige",
    "Pal Zileri",
    "Palace Skateboards",
    "Palm",
    "Panama",
    "Pantofola D'oro",
    "Paolo",
    "Parallel",
    "Paramo",
    "Pas Normal Studios",
    "Paul",
    "Paul And Joe",
    "Peal",
    "Pearce",
    "Pedaled",
    "Pepe",
    "Perks And Mini",
    "Permanent",
    "Peter Millar",
    "Peugeot",
    "Phiney Pet",
    "Picture Organic",
    "Piece Of White",
    "Pierre",
    "Pilgrim Surf + Supply",
    "Ping",
    "Pioneer Camp",
    "Pit Viper",
    "Plein Sport",
    "Polo",
    "Port",
    "Ports 1961",
    "Post",
    "Premiata",
    "President's",
    "Private White V.C.",
    "Pro",
    "Proenza Schouler",
    "Project",
    "Propaganda",
    "Pt01",
    "Pt05",
    "Public School",
    "Puma Select",
    "Purple Label",
    "Quay",
    "R13 Denim",
    "R2",
    "Rabbit",
    "Racing",
    "Raffaello Rossi",
    "Rag",
    "Railcar Fine Goods",
    "Ralph",
    "Rare",
    "Rave Skateboards",
    "Ray",
    "Realisation Par",
    "Rebel",
    "Red",
    "Red Bull",
    "Red Wing Shoes",
    "Redone",
    "Reebok Classics",
    "Reese Cooper",
    "Regatta",
    "Remi Relief",
    "Renato",
    "Rene Lezard",
    "Repetto",
    "Replumè",
    "Replay Hyperflex",
    "Resolute",
    "Rh+",
    "Rich",
    "Richard James",
    "Rier",
    "Rika",
    "Rip",
    "Road",
    "Robert Geller",
    "Roberto",
    "Robin",
    "Rochambeau",
    "Rodd",
    "Rogan",
    "Roger Vivier",
    "Rohé",
    "Rokin",
    "Ron",
    "Ron Dorff",
    "Rossignol 1907",
    "Rota",
    "Rotholz",
    "Rouje",
    "Royal",
    "Royer",
    "Rrl Ralph Lauren",
    "Rta",
    "Rubber",
    "Rubinacci",
    "Russell",
    "Rya",
    "Ryder",
    "Rylee + Cru",
    "S.N.S. Herning",
    "Sacai Man",
    "Saddle",
    "Saint Hilaire",
    "Saint Laurent Paris",
    "Saks Potts",
    "Salom",
    "Salvatore Ferragamo",
    "Samsøe & Samsøe",
    "Samuel",
    "Sandro Homme",
    "Santaniello",
    "Sartoria",
    "Sartoria Partenopea",
    "Sartorial",
    "Saturday",
    "Save",
    "Savile Row",
    "Scavini",
    "Schmoove",
    "Schnayderman's",
    "Schott",
    "Schyia",
    "Sci-Fi Fantasy",
    "Scott & Charters",
    "Sea Ny",
    "Sebago",
    "Second",
    "Sessun",
    "Seven For All Mankind",
    "Sezane",
    "Sf",
    "Shadow",
    "Shipley & Halmos",
    "Shoes Like Pottery",
    "Shops",
    "Sies Marjan",
    "Sigma",
    "Signum",
    "Simon Miller",
    "Sins",
    "Siviglia",
    "Six",
    "Sixth",
    "Skims",
    "Skull",
    "Slowear",
    "Sandro",
    "Smalto",
    "Soeur",
    "Solararis",
    "Solid & Striped",
    "Song For The Mute",
    "Sons",
    "South2 West8",
    "Spiewak & Sons",
    "Spring Court",
    "St. John",
    "Stampd",
    "Stance",
    "Stand Studio",
    "State Of Escape",
    "Steel",
    "Stella",
    "Stephane Kélian",
    "Stepney Workers Club",
    "Stetson",
    "Steve",
    "Steven Alan",
    "Story Mfg",
    "Strathberry",
    "Street",
    "Stutterheim",
    "Style Eyes",
    "Sui",
    "Suit",
    "Sun Buddies",
    "Sunday",
    "Supreme Community",
    "Svb",
    "Sweaty Betty",
    "Swedish Hasbeens",
    "Sweet Pants",
    "T-By Alexander Wang",
    "Tagliatore",
    "Takahiromiyashita",
    "Takeshy",
    "Talbot Runhof",
    "Tann's",
    "Tasmanian",
    "Taylor Stitch",
    "Ted",
    "Tei",
    "Tekla",
    "Tellason",
    "Tender",
    "Tenderloin",
    "Territory",
    "Testoni",
    "The",
    "The North Face Purple Label",
    "The Row",
    "The Upside",
    "Thierry Mugler",
    "Thom",
    "Thomas",
    "Thorogood",
    "Tibi",
    "Tie Your Tie",
    "Tiffany",
    "Timberland Boot Company",
    "Titleist",
    "Tods",
    "Tom",
    "Tommy",
    "Tomorrowland",
    "Tonello",
    "Topshop",
    "Tory",
    "Total",
    "Toto",
    "Tracksmith",
    "Tranoi",
    "Transit",
    "Tricker's",
    "True Religion Brand Jeans",
    "Truzi",
    "Tularosa",
    "Turnbull & Asser",
    "Twinset",
    "Twisted Tailor",
    "U.S. Navy",
    "Ugg Australia",
    "Ullajohnson",
    "Umbro Pro Training",
    "Unconditional",
    "Undercoverism",
    "Uniform Bridge",
    "Union",
    "United Arrows",
    "United Nude",
    "Universal Works",
    "Unknown London",
    "Unravel",
    "Urban Classics",
    "Ussen",
    "Vagabond",
    "Valstar",
    "Van Cleef",
    "Vans Vault",
    "Velva Sheen",
    "Versace Collection",
    "Vfiles",
    "Vicomte",
    "Victoria",
    "Vince",
    "Visvim Ict",
    "Vogue Eyewear",
    "Vollebak",
    "W.W.",
    "Wales Bonner",
    "Walk In Paris",
    "Walter Van Beirendonck",
    "Wandler",
    "Warrior",
    "We Are The Others",
    "Weather",
    "Weber",
    "Week",
    "Wempe",
    "Wendelborn",
    "Wes",
    "West Coast Choppers",
    "Western Hydrodynamic Research",
    "Whitesville",
    "Who",
    "Wigwam",
    "Wildfox",
    "William Lockie",
    "Willington",
    "Wills",
    "Willy Chavarria",
    "Wings + Horns",
    "Winston",
    "Wolsey",
    "Won Hundred",
    "Wood",
    "Wool & Prince",
    "Woolrich John Rich & Bros",
    "Wrangler Blue Bell",
    "Wrung Division",
    "Ww",
    "Xacus",
    "Xlarge",
    "Y/Project",
    "Y8",
    "Yardsale",
    "Yeezy",
    "Yellow",
    "Yeti",
    "Ymc You Must Create",
    "Yohji",
    "Yok",
    "You",
    "Young & Reckless",
    "Youth",
    "Yves Salomon",
    "Zadig",
    "Zanone",
    "Zara",
    "Zespà",
    "Zimmerli",
    "Zimmermann",
    "Zioni",
    "Zodiac",
    "Zone",
    "Zoo",
    "Zucca",
]


def upgrade() -> None:
    conn = op.get_bind()

    # Bulk insert with ON CONFLICT DO NOTHING (idempotent)
    for brand_name in BRANDS:
        conn.execute(
            text("""
                INSERT INTO product_attributes.brands (name)
                VALUES (:name)
                ON CONFLICT (name) DO NOTHING
            """),
            {"name": brand_name}
        )


def downgrade() -> None:
    conn = op.get_bind()

    # Remove only the brands added by this migration
    for brand_name in BRANDS:
        conn.execute(
            text("""
                DELETE FROM product_attributes.brands
                WHERE name = :name
            """),
            {"name": brand_name}
        )
