"""create_vinted_prospects_table

Revision ID: 3321c048edc7
Revises: 9d045c61f0bd
Create Date: 2026-01-19 12:37:08.906087+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3321c048edc7'
down_revision: Union[str, None] = '9d045c61f0bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vinted_prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vinted_user_id', sa.BigInteger(), nullable=False, comment='Vinted user ID'),
    sa.Column('login', sa.String(length=255), nullable=False, comment='Vinted username'),
    sa.Column('country_code', sa.String(length=10), nullable=True, comment='Country code (FR, DE, etc.)'),
    sa.Column('item_count', sa.Integer(), nullable=False, comment='Number of active items for sale'),
    sa.Column('total_items_count', sa.Integer(), nullable=False, comment='Total items ever listed'),
    sa.Column('feedback_count', sa.Integer(), nullable=False, comment='Number of feedback reviews'),
    sa.Column('feedback_reputation', sa.Numeric(precision=5, scale=2), nullable=True, comment='Feedback reputation score (0-5)'),
    sa.Column('is_business', sa.Boolean(), nullable=False, comment='Is a business account'),
    sa.Column('profile_url', sa.String(length=500), nullable=True, comment='URL to Vinted profile'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Prospection status: new, contacted, converted, ignored'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Admin notes about this prospect'),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this user was discovered'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last time stats were synced'),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True, comment='When the prospect was contacted'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='Admin user ID who triggered the discovery'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vinted_prospects')),
    sa.UniqueConstraint('vinted_user_id', name=op.f('uq_vinted_prospects_vinted_user_id'))
    )
    op.create_index('idx_vinted_prospects_country', 'vinted_prospects', ['country_code'], unique=False)
    op.create_index('idx_vinted_prospects_item_count', 'vinted_prospects', ['item_count'], unique=False)
    op.create_index('idx_vinted_prospects_status', 'vinted_prospects', ['status'], unique=False)
    op.create_index('idx_vinted_prospects_vinted_user_id', 'vinted_prospects', ['vinted_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vinted_prospects_vinted_user_id', table_name='vinted_prospects')
    op.drop_index('idx_vinted_prospects_status', table_name='vinted_prospects')
    op.drop_index('idx_vinted_prospects_item_count', table_name='vinted_prospects')
    op.drop_index('idx_vinted_prospects_country', table_name='vinted_prospects')
    op.drop_table('vinted_prospects')
    # ### end Alembic commands ###
