"""Update vinted_mapping with complete data

Revision ID: 20251224_2500
Revises: 20251224_2400
Create Date: 2025-12-24

Replaces all vinted_mapping data with 307 complete mappings.
"""

from alembic import op

revision = "20251224_2500"
down_revision = "20251224_2400"
branch_labels = None
depends_on = None

# (id, vinted_id, vinted_gender, my_category, my_gender, my_fit, my_length, my_rise, my_material, my_pattern, my_neckline, my_sleeve_length, is_default)
MAPPINGS = [
    (1, 1845, "women", "jeans", "women", "straight", None, None, None, None, None, None, True),
    (2, 1844, "women", "jeans", "women", "skinny", None, None, None, None, None, None, False),
    (3, 1841, "women", "jeans", "women", "flare", None, None, None, None, None, None, False),
    (4, 1839, "women", "jeans", "women", "relaxed", None, None, None, None, None, None, False),
    (5, 1842, "women", "jeans", "women", None, None, "high-rise", None, None, None, None, False),
    (6, 1840, "women", "jeans", "women", None, "cropped", None, None, None, None, None, False),
    (7, 1843, "women", "jeans", "women", None, None, None, None, None, None, None, False),
    (8, 1819, "men", "jeans", "men", "straight", None, None, None, None, None, None, True),
    (9, 1817, "men", "jeans", "men", "skinny", None, None, None, None, None, None, False),
    (10, 1818, "men", "jeans", "men", "slim", None, None, None, None, None, None, False),
    (11, 1816, "men", "jeans", "men", None, None, None, None, None, None, None, False),
    (12, 1559, "girls", "jeans", "girls", None, None, None, None, None, None, None, True),
    (13, 1560, "girls", "jeans", "girls", "slim", None, None, None, None, None, None, False),
    (14, 1696, "boys", "jeans", "boys", None, None, None, None, None, None, None, True),
    (15, 1697, "boys", "jeans", "boys", "slim", None, None, None, None, None, None, False),
    (16, 1059, "women", "dress", "women", None, None, None, None, None, None, None, True),
    (17, 178, "women", "dress", "women", None, "mini", None, None, None, None, None, False),
    (18, 1056, "women", "dress", "women", None, "midi", None, None, None, None, None, False),
    (19, 1055, "women", "dress", "women", None, "maxi", None, None, None, None, None, False),
    (20, 179, "women", "dress", "women", None, None, None, "denim", None, None, None, False),
    (21, 1775, "women", "dress", "women", None, None, None, None, None, None, None, False),
    (22, 1778, "women", "dress", "women", None, None, None, None, None, None, None, False),
    (23, 1060, "women", "dress", "women", None, None, None, None, None, None, None, False),
    (24, 1065, "women", "dress", "women", None, None, None, None, None, None, None, False),
    (25, 1779, "women", "dress", "women", None, None, None, None, None, None, None, False),
    (26, 1057, "women", "dress", "women", None, None, None, None, None, None, None, False),
    (27, 1061, "women", "dress", "women", None, None, None, None, None, None, None, False),
    (28, 1058, "women", "dress", "women", None, None, None, None, None, None, None, False),
    (29, 176, "women", "dress", "women", None, None, None, None, None, None, None, False),
    (30, 1554, "girls", "dress", "girls", None, "mini", None, None, None, None, None, True),
    (31, 1553, "girls", "dress", "girls", None, "maxi", None, None, None, None, None, False),
    (32, 221, "women", "t-shirt", "women", None, None, None, None, None, None, None, True),
    (33, 1806, "men", "t-shirt", "men", None, None, None, None, "solid", None, None, True),
    (34, 1807, "men", "t-shirt", "men", None, None, None, None, "printed", None, None, False),
    (35, 1808, "men", "t-shirt", "men", None, None, None, None, "striped", None, None, False),
    (36, 1810, "men", "t-shirt", "men", None, None, None, None, None, None, "long sleeve", False),
    (37, 1535, "girls", "t-shirt", "girls", None, None, None, None, None, None, None, True),
    (38, 1662, "boys", "t-shirt", "boys", None, None, None, None, None, None, None, True),
    (39, 534, "women", "tank-top", "women", None, None, None, None, None, None, None, True),
    (40, 560, "men", "tank-top", "men", None, None, None, None, None, None, None, True),
    (41, 1662, "boys", "tank-top", "boys", None, None, None, None, None, None, None, True),
    (42, 1535, "girls", "tank-top", "girls", None, None, None, None, None, None, None, True),
    (43, 222, "women", "shirt", "women", None, None, None, None, None, None, None, True),
    (44, 1803, "men", "shirt", "men", None, None, None, None, "solid", None, None, True),
    (45, 1801, "men", "shirt", "men", None, None, None, None, "checkered", None, None, False),
    (46, 1802, "men", "shirt", "men", None, None, None, "denim", None, None, None, False),
    (47, 1805, "men", "shirt", "men", None, None, None, None, "striped", None, None, False),
    (48, 1804, "men", "shirt", "men", None, None, None, None, "printed", None, None, False),
    (49, 1865, "men", "shirt", "men", None, None, None, None, None, None, None, False),
    (50, 1537, "girls", "shirt", "girls", None, None, None, None, None, None, None, True),
    (51, 1538, "girls", "shirt", "girls", None, None, None, None, None, None, "short sleeve", False),
    (52, 1539, "girls", "shirt", "girls", None, None, None, None, None, None, "long sleeve", False),
    (53, 1540, "girls", "shirt", "girls", None, None, None, None, None, None, "sleeveless", False),
    (54, 1664, "boys", "shirt", "boys", None, None, None, None, None, None, None, True),
    (55, 1665, "boys", "shirt", "boys", None, None, None, None, None, None, "short sleeve", False),
    (56, 1666, "boys", "shirt", "boys", None, None, None, None, None, None, "long sleeve", False),
    (57, 1667, "boys", "shirt", "boys", None, None, None, None, None, None, "sleeveless", False),
    (58, 1043, "women", "blouse", "women", None, None, None, None, None, None, None, True),
    (59, 223, "women", "blouse", "women", None, None, None, None, None, None, "short sleeve", False),
    (60, 224, "women", "blouse", "women", None, None, None, None, None, None, "long sleeve", False),
    (61, 225, "women", "blouse", "women", None, None, None, None, None, None, "3/4 sleeve", False),
    (62, 1537, "girls", "blouse", "girls", None, None, None, None, None, None, None, True),
    (63, 1837, "women", "top", "women", None, None, None, None, None, None, None, True),
    (64, 1042, "women", "top", "women", None, None, None, None, None, "off-shoulder", None, False),
    (65, 1044, "women", "top", "women", None, None, None, None, None, "halter", None, False),
    (66, 227, "women", "top", "women", None, None, None, None, None, None, None, False),
    (67, 228, "women", "top", "women", None, None, None, None, None, None, None, False),
    (68, 1541, "girls", "top", "girls", None, None, None, None, None, None, None, True),
    (69, 1878, "girls", "top", "girls", None, None, None, None, None, None, None, False),
    (70, 1041, "women", "crop-top", "women", None, None, None, None, None, None, None, True),
    (71, 1535, "girls", "crop-top", "girls", None, None, None, None, None, None, None, True),
    (72, 1835, "women", "bodysuit", "women", None, None, None, None, None, None, None, True),
    (73, 1041, "women", "bustier", "women", None, None, None, None, None, None, None, True),
    (74, 534, "women", "camisole", "women", None, None, None, None, None, None, None, True),
    (75, 1041, "women", "corset", "women", None, None, None, None, None, None, None, True),
    (76, 529, "women", "sweater", "women", None, None, None, None, None, None, None, True),
    (77, 1045, "women", "sweater", "women", None, None, None, None, None, "turtleneck", None, False),
    (78, 190, "women", "sweater", "women", None, None, None, None, None, "v-neck", None, False),
    (79, 191, "women", "sweater", "women", None, None, None, None, None, "turtleneck", None, False),
    (80, 1066, "women", "sweater", "women", None, None, None, None, None, None, None, False),
    (81, 1813, "men", "sweater", "men", None, None, None, None, None, "crew neck", None, True),
    (82, 264, "men", "sweater", "men", None, None, None, None, None, "v-neck", None, False),
    (83, 265, "men", "sweater", "men", None, None, None, None, None, "turtleneck", None, False),
    (84, 1815, "men", "sweater", "men", None, None, None, None, None, None, None, False),
    (85, 1542, "girls", "sweater", "girls", None, None, None, None, None, None, None, True),
    (86, 1543, "girls", "sweater", "girls", None, None, None, None, None, "v-neck", None, False),
    (87, 1544, "girls", "sweater", "girls", None, None, None, None, None, "turtleneck", None, False),
    (88, 1877, "girls", "sweater", "girls", None, None, None, None, None, None, None, False),
    (89, 1668, "boys", "sweater", "boys", None, None, None, None, None, None, None, True),
    (90, 1669, "boys", "sweater", "boys", None, None, None, None, None, "v-neck", None, False),
    (91, 1670, "boys", "sweater", "boys", None, None, None, None, None, "turtleneck", None, False),
    (92, 1887, "boys", "sweater", "boys", None, None, None, None, None, None, None, False),
    (93, 194, "women", "cardigan", "women", None, None, None, None, None, None, None, True),
    (94, 195, "women", "cardigan", "women", None, None, None, None, None, None, None, False),
    (95, 1874, "women", "cardigan", "women", None, None, None, None, None, None, None, False),
    (96, 266, "men", "cardigan", "men", None, None, None, None, None, None, None, True),
    (97, 1825, "men", "cardigan", "men", None, None, None, None, None, None, None, False),
    (98, 1551, "girls", "cardigan", "girls", None, None, None, None, None, None, None, True),
    (99, 1548, "girls", "cardigan", "girls", None, None, None, None, None, None, None, False),
    (100, 1673, "boys", "cardigan", "boys", None, None, None, None, None, None, None, True),
    (101, 196, "women", "sweatshirt", "women", None, None, None, None, None, None, None, True),
    (102, 192, "women", "sweatshirt", "women", None, None, None, None, None, None, None, False),
    (103, 197, "women", "sweatshirt", "women", None, None, None, None, None, None, None, False),
    (104, 1811, "men", "sweatshirt", "men", None, None, None, None, None, None, None, True),
    (105, 1814, "men", "sweatshirt", "men", None, None, None, None, None, None, None, False),
    (106, 268, "men", "sweatshirt", "men", None, None, None, None, None, None, None, False),
    (107, 1550, "girls", "sweatshirt", "girls", None, None, None, None, None, None, None, True),
    (108, 1672, "boys", "sweatshirt", "boys", None, None, None, None, None, None, None, True),
    (109, 577, "women", "hoodie", "women", None, None, None, None, None, None, None, True),
    (110, 267, "men", "hoodie", "men", None, None, None, None, None, None, None, True),
    (111, 1812, "men", "hoodie", "men", None, None, None, None, None, None, None, False),
    (112, 585, "men", "hoodie", "men", None, None, None, None, None, None, None, False),
    (113, 1550, "girls", "hoodie", "girls", None, None, None, None, None, None, None, True),
    (114, 1672, "boys", "hoodie", "boys", None, None, None, None, None, None, None, True),
    (115, 1086, "women", "fleece", "women", None, None, None, None, None, None, None, True),
    (116, 1858, "men", "fleece", "men", None, None, None, None, None, None, None, True),
    (117, 2547, "girls", "fleece", "girls", None, None, None, None, None, None, None, True),
    (118, 2575, "boys", "fleece", "boys", None, None, None, None, None, None, None, True),
    (119, 1086, "women", "half-zip", "women", None, None, None, None, None, None, None, True),
    (120, 1858, "men", "half-zip", "men", None, None, None, None, None, None, None, True),
    (121, 2547, "girls", "half-zip", "girls", None, None, None, None, None, None, None, True),
    (122, 2575, "boys", "half-zip", "boys", None, None, None, None, None, None, None, True),
    (123, 2529, "women", "overshirt", "women", None, None, None, None, None, None, None, True),
    (124, 2538, "men", "overshirt", "men", None, None, None, None, None, None, None, True),
    (125, 221, "women", "polo", "women", None, None, None, None, None, None, None, True),
    (126, 1809, "men", "polo", "men", None, None, None, None, None, None, None, True),
    (127, 1536, "girls", "polo", "girls", None, None, None, None, None, None, None, True),
    (128, 1663, "boys", "polo", "boys", None, None, None, None, None, None, None, True),
    (129, 1846, "women", "pants", "women", "straight", None, None, None, None, None, None, True),
    (130, 185, "women", "pants", "women", "skinny", None, None, None, None, None, None, False),
    (131, 187, "women", "pants", "women", "slim", None, None, None, None, None, None, False),
    (132, 1071, "women", "pants", "women", "loose", None, None, None, None, None, None, False),
    (133, 184, "women", "pants", "women", None, None, None, "leather", None, None, None, False),
    (134, 189, "women", "pants", "women", None, None, None, None, None, None, None, False),
    (135, 526, "women", "pants", "women", None, None, None, None, None, None, None, False),
    (136, 259, "men", "pants", "men", "skinny", None, None, None, None, None, None, True),
    (137, 260, "men", "pants", "men", "loose", None, None, None, None, None, None, False),
    (138, 263, "men", "pants", "men", None, None, None, None, None, None, None, False),
    (139, 583, "men", "pants", "men", None, None, None, None, None, None, None, False),
    (140, 1562, "girls", "pants", "girls", "flare", None, None, None, None, None, None, True),
    (141, 2079, "girls", "pants", "girls", None, None, None, None, None, None, None, False),
    (142, 1880, "girls", "pants", "girls", None, None, None, None, None, None, None, False),
    (143, 1698, "boys", "pants", "boys", "flare", None, None, None, None, None, None, True),
    (144, 2082, "boys", "pants", "boys", None, None, None, None, None, None, None, False),
    (145, 1870, "boys", "pants", "boys", None, None, None, None, None, None, None, False),
    (146, 1846, "women", "cargo-pants", "women", None, None, None, None, None, None, None, True),
    (147, 263, "men", "cargo-pants", "men", None, None, None, None, None, None, None, True),
    (148, 1880, "girls", "cargo-pants", "girls", None, None, None, None, None, None, None, True),
    (149, 1870, "boys", "cargo-pants", "boys", None, None, None, None, None, None, None, True),
    (150, 1070, "women", "chinos", "women", None, None, None, None, None, None, None, True),
    (151, 1820, "men", "chinos", "men", None, None, None, None, None, None, None, True),
    (152, 1880, "girls", "chinos", "girls", None, None, None, None, None, None, None, True),
    (153, 1870, "boys", "chinos", "boys", None, None, None, None, None, None, None, True),
    (154, 525, "women", "joggers", "women", None, None, None, None, None, None, None, True),
    (155, 1821, "men", "joggers", "men", None, None, None, None, None, None, None, True),
    (156, 1880, "girls", "joggers", "girls", None, None, None, None, None, None, None, True),
    (157, 1870, "boys", "joggers", "boys", None, None, None, None, None, None, None, True),
    (158, 189, "women", "dress-pants", "women", None, None, None, None, None, None, None, True),
    (159, 261, "men", "dress-pants", "men", None, None, None, None, None, None, None, True),
    (160, 1880, "girls", "dress-pants", "girls", None, None, None, None, None, None, None, True),
    (161, 1870, "boys", "dress-pants", "boys", None, None, None, None, None, None, None, True),
    (162, 1103, "women", "shorts", "women", None, None, None, None, None, None, None, True),
    (163, 1099, "women", "shorts", "women", None, None, "high-rise", None, None, None, None, False),
    (164, 1838, "women", "shorts", "women", None, None, "low-rise", None, None, None, None, False),
    (165, 538, "women", "shorts", "women", None, None, None, "denim", None, None, None, False),
    (166, 1100, "women", "shorts", "women", None, None, None, "leather", None, None, None, False),
    (167, 204, "women", "shorts", "women", None, None, None, None, None, None, None, False),
    (168, 205, "women", "shorts", "women", None, None, None, None, None, None, None, False),
    (169, 1822, "men", "shorts", "men", None, None, None, None, None, None, None, True),
    (170, 1823, "men", "shorts", "men", None, None, None, None, None, None, None, False),
    (171, 1824, "men", "shorts", "men", None, None, None, "denim", None, None, None, False),
    (172, 272, "men", "shorts", "men", None, None, None, None, None, None, None, False),
    (173, 1250, "girls", "shorts", "girls", None, None, None, None, None, None, None, True),
    (174, 1201, "boys", "shorts", "boys", None, None, None, None, None, None, None, True),
    (175, 203, "women", "bermuda", "women", None, None, None, None, None, None, None, True),
    (176, 271, "men", "bermuda", "men", None, None, None, None, None, None, None, True),
    (177, 1250, "girls", "bermuda", "girls", None, None, None, None, None, None, None, True),
    (178, 1201, "boys", "bermuda", "boys", None, None, None, None, None, None, None, True),
    (179, 198, "women", "skirt", "women", None, "mini", None, None, None, None, None, True),
    (180, 2927, "women", "skirt", "women", None, "knee length", None, None, None, None, None, False),
    (181, 199, "women", "skirt", "women", None, "midi", None, None, None, None, None, False),
    (182, 200, "women", "skirt", "women", None, "maxi", None, None, None, None, None, False),
    (183, 2928, "women", "skirt", "women", None, None, None, None, None, None, None, False),
    (184, 1248, "girls", "skirt", "girls", None, None, None, None, None, None, None, True),
    (185, 525, "women", "leggings", "women", None, None, None, None, None, None, None, True),
    (186, 1565, "girls", "leggings", "girls", None, None, None, None, None, None, None, True),
    (187, 1701, "boys", "leggings", "boys", None, None, None, None, None, None, None, True),
    (188, 2929, "women", "culottes", "women", None, None, None, None, None, None, None, True),
    (189, 1250, "girls", "culottes", "girls", None, None, None, None, None, None, None, True),
    (190, 1079, "women", "jacket", "women", None, None, None, "denim", None, None, None, True),
    (191, 2528, "women", "jacket", "women", None, None, None, None, None, None, None, False),
    (192, 2596, "women", "jacket", "women", None, None, None, None, None, None, None, False),
    (193, 2530, "women", "jacket", "women", None, None, None, None, None, None, None, False),
    (194, 571, "women", "jacket", "women", None, None, None, None, None, None, None, False),
    (195, 14, "women", "jacket", "women", None, None, None, None, None, None, None, False),
    (196, 1224, "men", "jacket", "men", None, None, None, "denim", None, None, None, True),
    (197, 2535, "men", "jacket", "men", None, None, None, None, None, None, None, False),
    (198, 2537, "men", "jacket", "men", None, None, None, None, None, None, None, False),
    (199, 1226, "men", "jacket", "men", None, None, None, None, None, None, None, False),
    (200, 2539, "men", "jacket", "men", None, None, None, None, None, None, None, False),
    (201, 581, "men", "jacket", "men", None, None, None, None, None, None, None, False),
    (202, 2546, "girls", "jacket", "girls", None, None, None, "denim", None, None, None, True),
    (203, 2574, "boys", "jacket", "boys", None, None, None, "denim", None, None, None, True),
    (204, 1078, "women", "bomber", "women", None, None, None, None, None, None, None, True),
    (205, 2531, "women", "bomber", "women", None, None, None, None, None, None, None, False),
    (206, 2527, "women", "bomber", "women", None, None, None, None, None, None, None, False),
    (207, 1223, "men", "bomber", "men", None, None, None, None, None, None, None, True),
    (208, 2550, "men", "bomber", "men", None, None, None, None, None, None, None, False),
    (209, 2534, "men", "bomber", "men", None, None, None, None, None, None, None, False),
    (210, 2545, "girls", "bomber", "girls", None, None, None, None, None, None, None, True),
    (211, 2573, "boys", "bomber", "boys", None, None, None, None, None, None, None, True),
    (212, 2614, "women", "puffer", "women", None, None, None, None, None, None, None, True),
    (213, 2536, "men", "puffer", "men", None, None, None, None, None, None, None, True),
    (214, 2548, "girls", "puffer", "girls", None, None, None, None, None, None, None, True),
    (215, 2576, "boys", "puffer", "boys", None, None, None, None, None, None, None, True),
    (216, 1076, "women", "coat", "women", None, None, None, None, None, None, None, True),
    (217, 2525, "women", "coat", "women", None, None, None, None, None, None, None, False),
    (218, 1090, "women", "coat", "women", None, None, None, None, None, None, None, False),
    (219, 2526, "women", "coat", "women", None, None, None, None, None, None, None, False),
    (220, 1861, "men", "coat", "men", None, None, None, None, None, None, None, True),
    (221, 1225, "men", "coat", "men", None, None, None, None, None, None, None, False),
    (222, 2533, "men", "coat", "men", None, None, None, None, None, None, None, False),
    (223, 2542, "girls", "coat", "girls", None, None, None, None, None, None, None, True),
    (224, 2540, "girls", "coat", "girls", None, None, None, None, None, None, None, False),
    (225, 2563, "boys", "coat", "boys", None, None, None, None, None, None, None, True),
    (226, 2561, "boys", "coat", "boys", None, None, None, None, None, None, None, False),
    (227, 1834, "women", "trench", "women", None, None, None, None, None, None, None, True),
    (228, 1230, "men", "trench", "men", None, None, None, None, None, None, None, True),
    (229, 2543, "girls", "trench", "girls", None, None, None, None, None, None, None, True),
    (230, 2564, "boys", "trench", "boys", None, None, None, None, None, None, None, True),
    (231, 1087, "women", "parka", "women", None, None, None, None, None, None, None, True),
    (232, 1227, "men", "parka", "men", None, None, None, None, None, None, None, True),
    (233, 2541, "girls", "parka", "girls", None, None, None, None, None, None, None, True),
    (234, 2562, "boys", "parka", "boys", None, None, None, None, None, None, None, True),
    (235, 1080, "women", "raincoat", "women", None, None, None, None, None, None, None, True),
    (236, 1859, "men", "raincoat", "men", None, None, None, None, None, None, None, True),
    (237, 2558, "girls", "raincoat", "girls", None, None, None, None, None, None, None, True),
    (238, 2606, "boys", "raincoat", "boys", None, None, None, None, None, None, None, True),
    (239, 2532, "women", "windbreaker", "women", None, None, None, None, None, None, None, True),
    (240, 2551, "men", "windbreaker", "men", None, None, None, None, None, None, None, True),
    (241, 2549, "girls", "windbreaker", "girls", None, None, None, None, None, None, None, True),
    (242, 2577, "boys", "windbreaker", "boys", None, None, None, None, None, None, None, True),
    (243, 532, "women", "blazer", "women", None, None, None, None, None, None, None, True),
    (244, 1786, "men", "blazer", "men", None, None, None, None, None, None, None, True),
    (245, 2544, "girls", "blazer", "girls", None, None, None, None, None, None, None, True),
    (246, 2571, "boys", "blazer", "boys", None, None, None, None, None, None, None, True),
    (247, 2524, "women", "vest", "women", None, None, None, None, None, None, None, True),
    (248, 2553, "men", "vest", "men", None, None, None, None, None, None, None, True),
    (249, 1518, "girls", "vest", "girls", None, None, None, None, None, None, None, True),
    (250, 1646, "boys", "vest", "boys", None, None, None, None, None, None, None, True),
    (251, 1773, "women", "cape", "women", None, None, None, None, None, None, None, True),
    (252, 1518, "girls", "cape", "girls", None, None, None, None, None, None, None, True),
    (253, 1067, "women", "poncho", "women", None, None, None, None, None, None, None, True),
    (254, 2552, "men", "poncho", "men", None, None, None, None, None, None, None, True),
    (255, 2556, "girls", "poncho", "girls", None, None, None, None, None, None, None, True),
    (256, 2604, "boys", "poncho", "boys", None, None, None, None, None, None, None, True),
    (257, 1067, "women", "kimono", "women", None, None, None, None, None, None, None, True),
    (258, 1131, "women", "jumpsuit", "women", None, None, None, None, None, None, None, True),
    (259, 1134, "women", "jumpsuit", "women", None, None, None, None, None, None, None, False),
    (260, 1568, "girls", "jumpsuit", "girls", None, None, None, None, None, None, None, True),
    (261, 1702, "boys", "jumpsuit", "boys", None, None, None, None, None, None, None, True),
    (262, 268, "men", "jumpsuit", "men", None, None, None, None, None, None, None, True),
    (263, 1568, "girls", "overalls", "girls", None, None, None, None, None, None, None, True),
    (264, 1702, "boys", "overalls", "boys", None, None, None, None, None, None, None, True),
    (265, 1134, "women", "overalls", "women", None, None, None, None, None, None, None, True),
    (266, 268, "men", "overalls", "men", None, None, None, None, None, None, None, True),
    (267, 1132, "women", "romper", "women", None, None, None, None, None, None, None, True),
    (268, 1568, "girls", "romper", "girls", None, None, None, None, None, None, None, True),
    (269, 1789, "men", "suit", "men", None, None, None, None, None, None, None, True),
    (270, 1787, "men", "suit", "men", None, None, None, None, None, None, None, False),
    (271, 1125, "women", "suit", "women", None, None, None, None, None, None, None, True),
    (272, 1125, "women", "womens-suit", "women", None, None, None, None, None, None, None, True),
    (273, 1126, "women", "womens-suit", "women", None, None, None, None, None, None, None, False),
    (274, 1128, "women", "womens-suit", "women", None, None, None, None, None, None, None, False),
    (275, 1789, "men", "tuxedo", "men", None, None, None, None, None, None, None, True),
    (276, 1788, "men", "suit-vest", "men", None, None, None, None, None, None, None, True),
    (277, 1551, "girls", "suit-vest", "girls", None, None, None, None, None, None, None, True),
    (278, 1673, "boys", "suit-vest", "boys", None, None, None, None, None, None, None, True),
    (279, 1671, "boys", "suit-vest", "boys", None, None, None, None, None, None, None, False),
    (280, 1439, "women", "sports-bra", "women", None, None, None, None, None, None, None, True),
    (281, 1253, "girls", "sports-bra", "girls", None, None, None, None, None, None, None, True),
    (282, 576, "women", "sports-top", "women", None, None, None, None, None, None, None, True),
    (283, 584, "men", "sports-top", "men", None, None, None, None, None, None, None, True),
    (284, 1253, "girls", "sports-top", "girls", None, None, None, None, None, None, None, True),
    (285, 1204, "boys", "sports-top", "boys", None, None, None, None, None, None, None, True),
    (286, 578, "women", "sports-shorts", "women", None, None, None, None, None, None, None, True),
    (287, 586, "men", "sports-shorts", "men", None, None, None, None, None, None, None, True),
    (288, 1253, "girls", "sports-shorts", "girls", None, None, None, None, None, None, None, True),
    (289, 1204, "boys", "sports-shorts", "boys", None, None, None, None, None, None, None, True),
    (290, 573, "women", "sports-leggings", "women", None, None, None, None, None, None, None, True),
    (291, 1565, "girls", "sports-leggings", "girls", None, None, None, None, None, None, None, True),
    (292, 3268, "women", "sports-jersey", "women", None, None, None, None, None, None, None, True),
    (293, 3267, "men", "sports-jersey", "men", None, None, None, None, None, None, None, True),
    (294, 1253, "girls", "sports-jersey", "girls", None, None, None, None, None, None, None, True),
    (295, 1204, "boys", "sports-jersey", "boys", None, None, None, None, None, None, None, True),
    (296, 572, "women", "tracksuit", "women", None, None, None, None, None, None, None, True),
    (297, 582, "men", "tracksuit", "men", None, None, None, None, None, None, None, True),
    (298, 1253, "girls", "tracksuit", "girls", None, None, None, None, None, None, None, True),
    (299, 1204, "boys", "tracksuit", "boys", None, None, None, None, None, None, None, True),
    (300, 218, "women", "swimsuit", "women", None, None, None, None, None, None, None, True),
    (301, 84, "men", "swimsuit", "men", None, None, None, None, None, None, None, True),
    (302, 1590, "girls", "swimsuit", "girls", None, None, None, None, None, None, None, True),
    (303, 1750, "boys", "swimsuit", "boys", None, None, None, None, None, None, None, True),
    (304, 219, "women", "bikini", "women", None, None, None, None, None, None, None, True),
    (305, 1592, "girls", "bikini", "girls", None, None, None, None, None, None, None, True),
    (306, 1868, "men", "t-shirt", "men", None, None, None, None, None, None, None, False),
    (307, 1886, "boys", "t-shirt", "boys", None, None, None, None, None, None, None, False),
]


def upgrade() -> None:
    # Drop FK constraint temporarily (vinted_categories is empty)
    op.execute("""
        ALTER TABLE vinted.vinted_mapping
        DROP CONSTRAINT IF EXISTS vinted_mapping_vinted_id_fkey
    """)
    print("  ✓ Dropped FK constraint temporarily")

    # Clear existing vinted_mapping
    op.execute("DELETE FROM vinted.vinted_mapping")
    print("  ✓ Cleared existing vinted_mapping")

    # Reset sequence
    op.execute("ALTER SEQUENCE vinted.vinted_mapping_id_seq RESTART WITH 1")

    # Insert all mappings
    for row in MAPPINGS:
        id_, vinted_id, vinted_gender, my_category, my_gender, my_fit, my_length, my_rise, my_material, my_pattern, my_neckline, my_sleeve_length, is_default = row

        def sql_val(v):
            if v is None:
                return "NULL"
            return f"'{v}'"

        sql = f"""
            INSERT INTO vinted.vinted_mapping 
            (id, vinted_id, vinted_gender, my_category, my_gender, my_fit, my_length, my_rise, my_material, my_pattern, my_neckline, my_sleeve_length, is_default)
            VALUES ({id_}, {vinted_id}, '{vinted_gender}', '{my_category}', '{my_gender}', {sql_val(my_fit)}, {sql_val(my_length)}, {sql_val(my_rise)}, {sql_val(my_material)}, {sql_val(my_pattern)}, {sql_val(my_neckline)}, {sql_val(my_sleeve_length)}, {str(is_default).lower()})
        """
        op.execute(sql)

    # Update sequence to next value
    op.execute("SELECT setval('vinted.vinted_mapping_id_seq', 307)")
    print(f"  ✓ Inserted {len(MAPPINGS)} vinted mappings")


def downgrade() -> None:
    # Not reverting - data migration
    pass
